[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.4"

[dev]
  framework = "create-react-app"
  command = "npm start"
  publish = "build"
  targetPort = 3000
